### ISSUE TITLE
Modularization: Breaking up main.yml into smaller playbooks or roles

### ISSUE THREAD

**Issue by ghost** [redhat-cop/ocp4-helpernode#111]
I am having a hard time with submitting a pull request for new functionality. Mostly because of the intermingling of service management and concerns. ex. installing and configuring PXE has tasks at line 29, 41, 131, 179, 192, 207, etc....

I was going to take a stab at starting the process of modularizing the main.yml. I'd like to break it up by service installs. 

- tasks
  - validate_vars.yml
  - setup_defaults.yml
  - download_artifacts.yml
  - pxe
    - dhcp.yml
    - tftp.yml
  - http.yml
  - dns.yml
  - haproxy.yml
  - etc...

or we could break it up into roles. 

Thoughts?

**Comment by christianh814** [comment]
I think modularizing would definitely make it more manageable. So I'm all for this! 

@bpradipt @therevoman @Prajyot-Parab Thoughts?

**Comment by Prajyot-Parab** [comment]
@christianh814 Breaking into tasks for modularizing should be good (no need of roles), we can reuse the same pieces of code and reorganize them with minor new additions. I would prefer having a single `main.yml` which includes everything based on conditions and rest pieces as independent service files.

**Comment by tosmi** [comment]
any updates on this? i'm thinking about splitting dhcp and pxe configuration. i'm running my own dhcp server in my lab and just need the pxe stuff configured on the bastion. this is currently not supported. i could work on a pull request, but modularization of main.yml would definitely help with this.

thanks for your hard work on ocp4-helpernode!
