### ISSUE TITLE
support OKD4

### ISSUE THREAD

**Issue by walidshaari** [redhat-cop/ocp4-helpernode#145]
the current repo has many settings which are wired to ocp4, it would be nice if we can expand it to OKD4

**Comment by christianh814** [comment]
Which sections, that cannot be altered by a `vars.yaml` file is hardcoded to OCP4? The playbook should work with OKD4 artifacts.

**Comment by walidshaari** [comment]
I see your point as long as we can override them as variables, yes, it should be fine or add them in the vars examples, I see one example that is close https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/docs/examples/vars-nightlies.yaml, will have to test it.

**Comment by christianh814** [comment]
Good point, it would be nice to at least have an example. If you could get a sample `vars.yaml` that works, I can include it in the examples

**Comment by christianh814** [comment]
@walidshaari Actually, it might not work. see #134  ...the new version of RHCOS will now require a new artefact that the helper doesn't account for currently.

As it stands, the helper will not work with OKD until version 4.6 comes out. I don't want to really make changes with a lot of conditionals if we just need to remove them for 4.6.

I'll leave this open and will come back this this once OCP v4.6 is GA.

**Comment by christianh814** [comment]
..well...maybe not https://github.com/coreos/fedora-coreos-tracker/issues/390#issuecomment-661986987

**Comment by walidshaari** [comment]
let me know if there is a task I can take.

**Comment by christianh814** [comment]
@walidshaari Please do! I would verify to see if it works "as is"
