### ISSUE TITLE
remove no longer required etcd srv records

### ISSUE THREAD

**Issue by dlbewley** [redhat-cop/ocp4-helpernode#147]
As of OCP 4.4, this can be removed at this point. Correct?

https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/templates/zonefile.j2#L56-L59

Per https://github.com/openshift/installer/issues/2740

**Comment by walidbahgat** [comment]
i think as long as 4.3 is suppirted this feature should be kept

**Comment by walidshaari** [comment]
they are harmless, maybe a default flag to indicate you are above 4.4? but then in 6 months time, almost everything should be 4.5+ if not 4.6, and that is UPI, IPI does not need them
