### ISSUE TITLE
Please allow control plane nodes and worker plane nodes to ingress-http and ingress-https

### ISSUE THREAD

**Issue by gefrickel** [redhat-cop/ocp4-helpernode#175]
Hi everyone.

I guess [169](https://github.com/RedHatOfficial/ocp4-helpernode/issues/169) was not very well formulated.

My request is to allow both, the worker nodes and the control nodes to be part of the load balancing configuration for ingress-http and ingress-https. 

Playing around with mastersSchedulable: true / false would be greatly supported by this. Having the load balancer configuration contain all the cluster members would easily allow to dynamically reconfigure the cluster.

Also the install with the control nodes marked Scheduleable would work. So I could use the control plane nodes in the ingress-http and ingress-https portion of the haproxy config.

Could you please add the control plane nodes as well as the worker nodes to the ingress-http and ingress-https portion of the haproxy config?

And yes, I still want to have worker nodes. And yes, they still should be part of the vars.yaml. And yes, they still should be in the load balancer config.

I assume that if you do not run the control plane as Schedulable there is no negative effect as the haproxy load balancer will not "balance" across the "unavailable" endpoints. So this should be a trasparent change to the existing way how it already works.
Also it would allow for "smaller" three node deployments in resource constrained environments.

Kind regards

**Comment by christianh814** [comment]
This sounds reasonable, going to take a look at it in the next couple of weeks. Thanks!

**Comment by salanisor** [comment]
Recently watched episode 129 of [TGI Kubernetes](https://www.youtube.com/watch?v=ibrDDaLD6Ks) which they discuss running unnecessary workload on the control plane and something malicious gaining access to your etcd dataz for example. If enabled, would this be called out as an anti-pattern?

**Comment by christianh814** [comment]
> Recently watched episode 129 of [TGI Kubernetes](https://www.youtube.com/watch?v=ibrDDaLD6Ks) which they discuss running unnecessary workload on the control plane and something malicious gaining access to your etcd dataz for example. If enabled, would this be called out as an anti-pattern?

In general, yes. You want to minimize the attack surface. However, it's relatively okay if you're using something like PSP, Katacontainers, or (like OCP) use SCC.

You also need to keep into account which containers are "privileged" containers

**Comment by AhwiniMirajkar** [comment]
I want to work on this
