### ISSUE TITLE
External access to Libvirt DHCP cluster.

### ISSUE THREAD

**Issue by cgoguyer** [redhat-cop/ocp4-helpernode#183]
As an enhancement, it would be great to have in the "Libvirt DHCP install" playbook an option to add an external access to the console and API (outside the virt host server). So to add a bridge connection to the helper VM and to add an external DNS zone in DNS server automatically. Then we could connect from an external laptop to the cluster.

**Comment by bassplay3r** [comment]
I like this . I got around this by adding a 2nd line to the helper kickstart file for an external address. Our CI is able to connect to the helper and run whatever tests it needs but it does not give you full access from the outside.

**Comment by dmi3mis** [comment]
I like this too. It would be helpfull.
Now as a workaround you can add this configuration file to enable external access to haproxy cluster in libvirt server

cat /etc/firewalld/direct.xml

<?xml version="1.0" encoding="utf-8"?>
<direct>
  <passthrough ipv="ipv4">-t nat -I PREROUTING -i <external_ethname_replace_this> -p tcp --dport 80 -j DNAT --to-destination 192.168.7.77:80</passthrough>
  <passthrough ipv="ipv4">-t nat -I PREROUTING -i <external_ethname_replace_this>  -p tcp --dport 6443 -j DNAT --to-destination 192.168.7.77:6443</passthrough>
  <passthrough ipv="ipv4">-t nat -I PREROUTING -i <external_ethname_replace_this>  -p tcp --dport 443 -j DNAT --to-destination 192.168.7.77:443</passthrough>
  <passthrough ipv="ipv4">-t filter -I FORWARD 1 -m state -d 192.168.7.0/24 --state NEW,RELATED,ESTABLISHED -j ACCEPT</passthrough>
</direct>

systemctl reload firewalld
