### ISSUE TITLE
Help needed : Inappropriate ioctl for device 

### ISSUE THREAD

**Issue by myki57** [redhat-cop/ocp4-helpernode#190]
Hi,
I have a (new) issue after having upgrade my NAS with a SSD. My VM are 4vCPU/16GBram/50GB SSD HD images 

After installing successfully my bootstrap, the first master node didn't successfully install and give me this error :  
![Capture d’écran 2020-12-04 à 12 46 42](https://user-images.githubusercontent.com/11648026/101332405-86dea780-3875-11eb-973a-ab0210cee7ea.png)

Any thought on that ?

Thanks for your help.

**Comment by christianh814** [comment]
What did oyu pass as the disk parameter?

**Comment by christianh814** [comment]
Verify that [the Disk](https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/docs/examples/vars.yaml#L2) is the correct one.

**Comment by myki57** [comment]
Hi Christian,
I didn't explicitly specific disk parameter. What do you mean by disk parameters ?

The only specific thing that I done was to create an install-config for three node cluster via this parameters : 
compute:
- name: worker
  platform: {}
  replicas: 0

**Comment by myki57** [comment]
I tried to rease disk and reinstall many times without success. Same error.
