### ISSUE TITLE
Unarchiving fails

### ISSUE THREAD

**Issue by mmiller7** [redhat-cop/ocp4-helpernode#191]
During setup on RHEL 7.9 with all updates installed, EPEL Ansible 2.9.15, the playbook is failing with the following error:

```
TASK [Unarchiving OCP4 Installer] **********************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to find handler 
for \"/usr/local/src/openshift-install-linux.tar.gz\". Make sure the required
command to extract the file is installed. Command \"/usr/bin/unzip\" could not
handle archive. Command \"/usr/bin/gtar\" could not handle archive."}
```

After some additional troubleshooting, it appears if the download is interrupted the scripts never attempt to clean up the partial download, nor do they re-download the tar-archive.  It must be manually located, deleted, and re-run (and then hope it doesn't fail again).

Expected result:
I would expect if the download is interrupted it would retry, or the file deleted so it can retry the next runtime.  Alternatively, validation of a checksum or something to ensure the downloaded file is in fact not tampered with (and more appropriate error) would be good.

**Comment by christianh814** [comment]
> Expected result:
> I would expect if the download is interrupted it would retry, or the file deleted so it can retry the next runtime. Alternatively, validation of a checksum or something to ensure the downloaded file is in fact not tampered with (and more appropriate error) would be good.

This is actually a good idea!

In the meantime you can pass `-e force_ocp_download=true`

**Comment by m-ayan-k** [comment]
Hey, I would like to contribute to your project. So, could tell me what other thing should I know other than HTML.

**Comment by saumyahada** [comment]
Hey, I am a beginner can you help me in getting started. I know c and html what else skills I require?

**Comment by AhwiniMirajkar** [comment]
I want to work on this
