### ISSUE TITLE
firewalld module not found in main.yml

### ISSUE THREAD

**Issue by cunlifs** [redhat-cop/ocp4-helpernode#216]
Running helpernode playbook, I get an error stating that firewalld module can't be found:

_module.helpernode.null_resource.config (remote-exec): Running ocp4-helpernode playbook...
module.helpernode.null_resource.config (remote-exec): Using /root/ocp4-helpernode/ansible.cfg as config file
module.helpernode.null_resource.config (remote-exec): ERROR! couldn't resolve module/action 'firewalld'. This often indicates a misspelling, missing collection, or incorrect module path.
module.helpernode.null_resource.config (remote-exec): 
module.helpernode.null_resource.config (remote-exec): The error appears to be in '/root/ocp4-helpernode/tasks/main.yml': line 133, column 5, but may
module.helpernode.null_resource.config (remote-exec): be elsewhere in the file depending on the exact syntax problem.
module.helpernode.null_resource.config (remote-exec): 
module.helpernode.null_resource.config (remote-exec): The offending line appears to be:
module.helpernode.null_resource.config (remote-exec): 
module.helpernode.null_resource.config (remote-exec): 
module.helpernode.null_resource.config (remote-exec):   - name: Open up firewall ports
module.helpernode.null_resource.config (remote-exec):     ^ here

Logged onto the helper node and confirmed ansible-doc cannot see that short name:

[root@uk-1314-bastion ~]# ansible-doc firewalld
[WARNING]: module firewalld not found in: /root/.ansible/plugins/modules:/usr/share/ansible/plugins/modules:/usr/local/lib/python3.6/site-
packages/ansible/modules

but can see the full name:
[root@uk-1314-bastion ~]# ansible-doc ansible.posix.firewalld
> ANSIBLE.POSIX.FIREWALLD    (/usr/local/lib/python3.6/site-packages/ansible_collections/ansible/posix/plugins/modules/firewalld.py)
        This module allows for addition or deletion of services and ports (either TCP or UDP) in either running or
        permanent firewalld rules.

Copied module to non-posix plugin directory and the install continued.

**Comment by salanisor** [comment]
@cunlifs what OS version are you running?

**Comment by cunlifs** [comment]
@salanisor - Red Hat Enterprise Linux 8.2 (Ootpa) & ansible 2.10.6

**Comment by salanisor** [comment]
@cunlifs I installed Ansible via pip `pip3 install ansible==2.10.6` running RHEL 8.2 [Reference-1] - but I am not running into any problems once I activate my virtual environment.

The only catch for whatever reason when installing pip without `--user` it is putting the Ansible binary under `~/.local/bin` which I do not have exported [Reference-2].

I guess what I am trying to get at is how did you arrive at this state.

- How did you install Ansible?
- How are you executing the playbook?
- Kindly provide the output of `ansible-config dump --only-changed`
- Can you kindly rerun the playbook with verbose enable and post the results please e.g; `ansible-playbook -e @vars.yaml tasks/main.yml -vvvv`

Reference:
[1]
```
dnf info redhat-release
Updating Subscription Management repositories.
Last metadata expiration check: 0:35:49 ago on Mon 15 Mar 2021 09:32:51 AM CDT.
Installed Packages
Name         : redhat-release
Version      : 8.2
Release      : 1.0.el8
Architecture : x86_64
Size         : 52 k
Source       : redhat-release-8.2-1.0.el8.src.rpm
Repository   : @System
From repo    : rhel-8-for-x86_64-baseos-rpms
Summary      : Red Hat Enterprise Linux release file
License      : GPLv2
Description  : Red Hat Enterprise Linux release files
```

[2]
```
/root/.local/bin/ansible-playbook -e @vars.yaml tasks/main.yml -vvvv
```

**Comment by salanisor** [comment]
I've been keeping an eye out for this and a bug has been raised under the [ansible-collections](https://github.com/ansible-collections/community.general/issues/1940) repo. Surprised that I didn't hit this bug. Are you still experiencing this isue? @cunlifs
