### ISSUE TITLE
After running ansible playbook to set up helper node, am unable to get PXE boot to work

### ISSUE THREAD

**Issue by steve-delillo** [redhat-cop/ocp4-helpernode#232]
Using RHEL8.3 for our helper node (infrastructure node).  After successfully running the playbook, generated the manifests and ignition files and copied them into path: /var/www/html/ignition/

We are using the vars.yaml to generate the PXE default file and pull down the latest nightly build [as I show below].

This is a bare-metal install - no virtual machines for this setup.

IPs on the 192.168.7* network are private.
IPs on the 9.11.136* network are public.

When I go to PXE boot the bootstrap node (I am doing them in order, starting with bootstrap), it never starts loading RHCOS on the bootstrap.  The PXE boot process just times out as I show below.  You can see that it knows that media is present for the boostrap node's MAC address, but it simply times out.  At the very least, I would expect it to show the menu for the choices to install bootstrap, master, and worker.
<img width="518" alt="image" src="https://user-images.githubusercontent.com/84864338/124627663-99818500-de34-11eb-9a19-66aa1ec9225f.png">

Here is my vars.yaml file:

# cat vars.yaml

<img width="496" alt="image" src="https://user-images.githubusercontent.com/84864338/124630436-4826c500-de37-11eb-9231-b8019a1472c0.png">
<img width="1447" alt="image" src="https://user-images.githubusercontent.com/84864338/124630472-507f0000-de37-11eb-9fda-8e93846573fc.png">

All of the necessary services seem to be running:

~# /usr/local/bin/helpernodecheck services
Status of services:
===================
Status of dhcpd svc 		->    Active: active (running) since Tue 2021-07-06 07:39:58 MST; 39min ago
Status of named svc 		->    Active: active (running) since Tue 2021-07-06 07:39:59 MST; 39min ago
Status of haproxy svc 		->    Active: active (running) since Tue 2021-07-06 07:39:57 MST; 39min ago
Status of httpd svc 		->    Active: active (running) since Tue 2021-07-06 07:39:55 MST; 39min ago
Status of tftp svc 		->    Active: active (running) since Tue 2021-07-06 08:08:46 MST; 11min ago
Unit keepalived.service could not be found.
Status of keepalived svc 		-> 
Unit local-registry.service could not be found.
Status of local-registry svc 		-> 

Here is the default file for PXE boot that we are trying to use:

~# cat /var/lib/tftpboot/pxelinux.cfg/default
default menu.c32   
 prompt 0   
 timeout 900
 ONTIMEOUT   
 menu title ######## PXE Boot Menu ########  
 label 1  
 menu label ^1) Install Bootstrap Node
 kernel rhcos/kernel
 append initrd=rhcos/initramfs.img nomodeset rd.neednet=1 ip=dhcp coreos.inst=yes coreos.inst.install_dev=sda  coreos.inst.image_url=http://192.168.7.77:8080/install/bios.raw.gz  coreos.inst.ignition_url=http://192.168.7.77:8080/ignition/bootstrap.ign
 label 2  
 menu label ^2) Install Master Node
 kernel rhcos/kernel
 append initrd=rhcos/initramfs.img nomodeset rd.neednet=1 ip=dhcp coreos.inst=yes coreos.inst.install_dev=sda  coreos.inst.image_url=http://192.168.7.77:8080/install/bios.raw.gz  coreos.inst.ignition_url=http://192.168.7.77:8080/ignition/master.ign
 label 3  
 menu label ^3) Install Worker Node
 kernel rhcos/kernel
 append initrd=rhcos/initramfs.img nomodeset rd.neednet=1 ip=dhcp coreos.inst=yes coreos.inst.install_dev=sda  coreos.inst.image_url=http://192.168.7.77:8080/install/bios.raw.gz  coreos.inst.ignition_url=http://192.168.7.77:8080/ignition/worker.ign

This is what my pxelinux.cfg directory looks like:
<img width="852" alt="image" src="https://user-images.githubusercontent.com/84864338/124933524-cf4f7680-dfb8-11eb-8521-88dd23fa3ccd.png">

**Comment by steve-delillo** [comment]
We were able to finally get the bootstrap server loaded by:
1) Using `uefi: true` in the vars.yaml.  This way, the bootstrap node used a .efi file in /var/lib/tftpboot/grub2/ to load RHCOS
2) The documentation for the ocp4-helpernode vars.yaml documentation does not have the case for a bare-metal install where instead of using metal-bios-raw.gz for the `ocp_bios:` variable, the user needs to use the rootfs image for that release.

**Comment by christianh814** [comment]
@steve-delillo Would you mind pointing to where it would make most sense to have this documented? 

Thanks for pointing this out!

**Comment by steve-delillo** [comment]
Hi @christianh814 .  No problem.  Glad to help.

I think the best place to show this would be in the vars.yaml documentation - just so folks using this playbook don't have to constantly click back-and-forth between pages.  Thinking that the best place in the Specifying Artifacts section shown below.  Maybe have an example for a bare-metal install (like I am doing):
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/84864338/125213427-2da18100-e267-11eb-9c95-36209d3568d6.png">

For example, I have the following in my vars.yaml:
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/84864338/125213528-5295f400-e267-11eb-99cc-6f775a764e3a.png">
