### ISSUE TITLE
authentication operator not available.

### ISSUE THREAD

**Issue by kumaravel2** [redhat-cop/ocp4-helpernode#242]
![image](https://user-images.githubusercontent.com/78522990/127739538-23459585-7e8a-4fd2-bd39-70844ef20403.png)

![image](https://user-images.githubusercontent.com/78522990/127739548-437fe451-b976-4d8d-a26f-fae53c99e503.png)

[ocpuser@adminnode ~]$ oc get clusterversion
NAME      VERSION                         AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.7.0-0.okd-2021-07-03-190901   True        False         18d     Cluster version is 4.7.0-0.okd-2021-07-03-190901

**Comment by christianh814** [comment]
Usually the authentication fails when the router is failing. What do the ingress pods say in the logs? Did the router fully roll out?

**Comment by kumaravel2** [comment]
thanks, the issue seems to be on the ingress pods, I managed to reinstall and the issue did not recur.
