### ISSUE TITLE
NFS provisioner image update in 4.7 +

### ISSUE THREAD

**Issue by jaymiracola** [redhat-cop/ocp4-helpernode#243]
NFS Image 3.x has issues related to this issue https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/25 . Current release k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2 fixes this.

**Comment by oliverbutanowitz** [comment]
Had the same issue in new provisioned OCP 4.8.2 using actual ocp4-helpernode.
For reference, here's my workaround to fix it in (the already installed) OCP:
```
oc patch deployment nfs-client-provisioner -p  '{"spec":{"template":{"spec":{"containers":[{"name": "nfs-client-provisioner", "image":"k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2"}]}}}}' -nnfs-provisioner
```

**Comment by christianh814** [comment]
Good catch! I'll update the image!

**Comment by simararneja** [comment]
Would the newer build (4.0.2) be backwards compatible with 4.6.x version of OCP ?
