### ISSUE TITLE
Mac address needed to be lower case in vars.ymal

### ISSUE THREAD

**Issue by spazgirl** [redhat-cop/ocp4-helpernode#244]
On the vars.yaml documentation page please add that for Power VM dhcp you will fail to install vm's with Bootstrap failing at 
Client ::ffff :129.40.80.77 finished /boot/grub2/powerpc-ieee1275/test.mod    and go no further.  and drop you in grub. It took me a while to figure out..
https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/docs/vars-doc.md
Maybe add note saying lower case only or will not build cluster, at the step to add vars.yaml I think it would be very helpful to people who are new to OCP setup.
Here is what  /var/log/messages shows you when you try to install bootstrap
# tail -f /var/log/messages
Jul 28 18:23:03 p215n71 systemd[1]: Stopped Starts TFTP on boot because of reasons.
Jul 28 18:23:03 p215n71 systemd[1]: Started Starts TFTP on boot because of reasons.
Jul 28 18:23:03 p215n71 systemd[1]: helper-tftp.service: Succeeded.
Jul 28 18:23:16 p215n71 systemd[1]: Started Session 4 of user root.
Jul 28 18:23:16 p215n71 systemd-logind[987]: New session 4 of user root.
Jul 28 18:23:33 p215n71 systemd[1]: helper-tftp.service: Service RestartSec=30s expired, scheduling restart.
Jul 28 18:23:33 p215n71 systemd[1]: helper-tftp.service: Scheduled restart job, restart counter is at 38.
Jul 28 18:23:33 p215n71 systemd[1]: Stopped Starts TFTP on boot because of reasons.
Jul 28 18:23:33 p215n71 systemd[1]: Started Starts TFTP on boot because of reasons.
Jul 28 18:23:33 p215n71 systemd[1]: helper-tftp.service: Succeeded.
Jul 28 18:24:03 p215n71 systemd[1]: helper-tftp.service: Service RestartSec=30s expired, scheduling restart.
Jul 28 18:24:03 p215n71 systemd[1]: helper-tftp.service: Scheduled restart job, restart counter is at 39.
Jul 28 18:24:03 p215n71 systemd[1]: Stopped Starts TFTP on boot because of reasons.
Jul 28 18:24:03 p215n71 systemd[1]: Started Starts TFTP on boot because of reasons.
Jul 28 18:24:03 p215n71 systemd[1]: helper-tftp.service: Succeeded.
Jul 28 18:24:33 p215n71 systemd[1]: helper-tftp.service: Service RestartSec=30s expired, scheduling restart.
Jul 28 18:24:33 p215n71 systemd[1]: helper-tftp.service: Scheduled restart job, restart counter is at 40.
Jul 28 18:24:33 p215n71 systemd[1]: Stopped Starts TFTP on boot because of reasons.
Jul 28 18:24:33 p215n71 systemd[1]: Started Starts TFTP on boot because of reasons.
Jul 28 18:24:33 p215n71 systemd[1]: helper-tftp.service: Succeeded.
Jul 28 18:25:03 p215n71 systemd[1]: helper-tftp.service: Service RestartSec=30s expired, scheduling restart.
Jul 28 18:25:03 p215n71 systemd[1]: helper-tftp.service: Scheduled restart job, restart counter is at 41.
Jul 28 18:25:03 p215n71 systemd[1]: Stopped Starts TFTP on boot because of reasons.
Jul 28 18:25:03 p215n71 systemd[1]: Started Starts TFTP on boot because of reasons.
Jul 28 18:25:03 p215n71 systemd[1]: helper-tftp.service: Succeeded.
Jul 28 18:25:11 p215n71 dhcpd[40377]: BOOTREQUEST from be:c6:e4:e3:03:03 via env3
Jul 28 18:25:11 p215n71 dhcpd[40377]: BOOTREPLY for 129.40.80.77 to bootstrap (be:c6:e4:e3:03:03) via env3
Jul 28 18:25:11 p215n71 in.tftpd[40944]: Client ::ffff:129.40.80.77 finished boot/grub2/powerpc-ieee1275/core.elf
Jul 28 18:25:19 p215n71 in.tftpd[40949]: Client ::ffff:129.40.80.77 finished /boot/grub2/powerpc-ieee1275/normal.mod
Jul 28 18:25:19 p215n71 in.tftpd[40950]: Client ::ffff:129.40.80.77 finished /boot/grub2/powerpc-ieee1275/terminal.mod
Jul 28 18:25:20 p215n71 in.tftpd[40951]: Client ::ffff:129.40.80.77 finished /boot/grub2/powerpc-ieee1275/crypto.mod
Jul 28 18:25:20 p215n71 in.tftpd[40952]: Client ::ffff:129.40.80.77 finished /boot/grub2/powerpc-ieee1275/gettext.mod
Jul 28 18:25:20 p215n71 in.tftpd[40953]: Client ::ffff:129.40.80.77 finished /boot/grub2/powerpc-ieee1275/gzio.mod
Jul 28 18:25:20 p215n71 in.tftpd[40954]: Client ::ffff:129.40.80.77 finished /boot/grub2/powerpc-ieee1275/gcry_crc.mod
Jul 28 18:25:31 p215n71 in.tftpd[40964]: Client ::ffff:129.40.80.77 finished boot/grub2/powerpc-ieee1275/grub.cfg
Jul 28 18:25:32 p215n71 in.tftpd[40965]: Client ::ffff:129.40.80.77 finished /boot/grub2/powerpc-ieee1275/command.lst
Jul 28 18:25:33 p215n71 in.tftpd[40966]: Client ::ffff:129.40.80.77 finished /boot/grub2/powerpc-ieee1275/fs.lst
Jul 28 18:25:33 p215n71 systemd[1]: helper-tftp.service: Service RestartSec=30s expired, scheduling restart.
Jul 28 18:25:33 p215n71 systemd[1]: helper-tftp.service: Scheduled restart job, restart counter is at 42.
Jul 28 18:25:33 p215n71 systemd[1]: Stopped Starts TFTP on boot because of reasons.
Jul 28 18:25:33 p215n71 systemd[1]: Started Starts TFTP on boot because of reasons.
Jul 28 18:25:33 p215n71 systemd[1]: helper-tftp.service: Succeeded.
Jul 28 18:25:34 p215n71 in.tftpd[40970]: Client ::ffff:129.40.80.77 finished /boot/grub2/powerpc-ieee1275/crypto.lst
Jul 28 18:25:35 p215n71 in.tftpd[40971]: Client ::ffff:129.40.80.77 finished /boot/grub2/powerpc-ieee1275/terminal.lst
Jul 28 18:25:36 p215n71 in.tftpd[40972]: Client ::ffff:129.40.80.77 finished boot/grub2/powerpc-ieee1275/grub.cfg
Jul 28 18:25:37 p215n71 in.tftpd[40973]: Client ::ffff:129.40.80.77 finished /boot/grub2/powerpc-ieee1275/configfile.mod
Jul 28 18:25:38 p215n71 in.tftpd[40974]: Client ::ffff:129.40.80.77 finished boot/grub2/grub.cfg
Jul 28 18:25:38 p215n71 in.tftpd[40975]: Client ::ffff:129.40.80.77 finished /boot/grub2/powerpc-ieee1275/test.mod
Jul 28 18:26:03 p215n71 systemd[1]: helper-tftp.service: Service RestartSec=30s expired, scheduling restart.
Jul 28 18:26:03 p215n71 systemd[1]: helper-tftp.service: Scheduled restart job, restart counter is at 43.
Jul 28 18:26:03 p215n71 systemd[1]: Stopped Starts TFTP on boot because of reasons.
Jul 28 18:26:03 p215n71 systemd[1]: Started Starts TFTP on boot because of reasons.
Jul 28 18:26:03 p215n71 systemd[1]: helper-tftp.service: Succeeded.
Jul 28 18:26:33 p215n71 systemd[1]: helper-tftp.service: Service RestartSec=30s expired, scheduling restart.
Jul 28 18:26:33 p215n71 systemd[1]: helper-tftp.service: Scheduled restart job, restart counter is at 44.
Jul 28 18:26:33 p215n71 systemd[1]: Stopped Starts TFTP on boot because of reasons.
Jul 28 18:26:33 p215n71 systemd[1]: Started Starts TFTP on boot because of reasons.
Jul 28 18:26:33 p215n71 systemd[1]: helper-tftp.service: Succeeded.
Jul 28 18:27:03 p215n71 systemd[1]: helper-tftp.service: Service RestartSec=30s expired, scheduling restart.

**Comment by christianh814** [comment]
It should always convert to lowercase for you.

https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/templates/dhcpd.conf.j2#L23

And in your log it says

> Jul 28 18:25:11 p215n71 dhcpd[40377]: BOOTREQUEST from be:c6:e4:e3:03:03 via env3

So it looks lowercase. Can you verify that it's actually lowercase in the dhcpd.conf file?

**Comment by spazgirl** [comment]
When I run the playbook with the vars.yaml mac addresses in uppercase they stay in upper case.  I can not look to see if they stay upper in dhcpd.conf since i fixed my issue and reran playbook.  but that is what is failing when bootstrap fails to boot.
As soon as I put in lower case in vars.yaml and run playbook again and do the rest of the setup  it installs.
 
Thank you,Teri WoodPower Systems Technical Specialist   IBM Garage for Systems, IBM Technology Sales Americas
+1-720-349-6892 OfficeEmail: ***@***.***
  
 
 
----- Original message -----From: "Christian Hernandez" ***@***.***>To: "RedHatOfficial/ocp4-helpernode" ***@***.***>Cc: "spazgirl" ***@***.***>, "Author" ***@***.***>Subject: [EXTERNAL] Re: [RedHatOfficial/ocp4-helpernode] Mac address needed to be lower case in vars.ymal (#244)Date: Wed, Aug 11, 2021 4:48 PM      It should always convert to lowercase for you. https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/templates/dhcpd.conf.j2#L23 And in your log it says Jul 28 18:25:11 p215n71 dhcpd[40377]: BOOTREQUEST from be:c6:e4:e3:03:03 via env3    ZjQcmQRYFpfptBannerStart  

This Message Is From an External Sender
This message came from outside your organization. ZjQcmQRYFpfptBannerEnd 
 
It should always convert to lowercase for you.
https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/templates/dhcpd.conf.j2#L23
And in your log it says
Jul 28 18:25:11 p215n71 dhcpd[40377]: BOOTREQUEST from be:c6:e4:e3:03:03 via env3
So it looks lowercase. Can you verify that it's actually lowercase in the dhcpd.conf file?
