### ISSUE TITLE
DNS Container won't start when using Helpernode V2

### ISSUE THREAD

**Issue by itester394** [redhat-cop/ocp4-helpernode#260]
Trying to deploy an Openshift Cluster using Helpernode V2
The DNS Container won't start or even gets created : 

Steps to reporoduce:-

-----
[root@ib-ocp4helpernodev2ipi ~]# helpernodectl start --config helpernode.yaml dns --log-level=debug
DEBU[0000] Using file located at $HOME/.helpernodectl.yaml
INFO[0000] Using --config file:helpernode.yaml
DEBU[0000] Reading configuration file
DEBU[0000] Using quay.io as the registry
DEBU[0000] Using registry : quay.io
DEBU[0000] dns:quay.io/helpernode/dns:latest
DEBU[0000] dhcp:quay.io/helpernode/dhcp:latest
DEBU[0000] http:quay.io/helpernode/http:latest
DEBU[0000] loadbalancer:quay.io/helpernode/loadbalancer:latest
DEBU[0000] pxe:quay.io/helpernode/pxe:latest
DEBU[0000] starting: dns
INFO[0000] [dns]
INFO[0000] Found a configuration
INFO[0000] RUNNING PREFLIGHT TASKS
INFO[0000] Starting Systemd Checks
INFO[0000] Preflight checks for Systemd                  Systemd Issues=0
INFO[0000] Starting Port Checks
DEBU[0000] Testing port 69 on protocol udp
DEBU[0000] Testing port 443 on protocol tcp
DEBU[0000] Testing port 6443 on protocol tcp
DEBU[0000] Testing port 9090 on protocol tcp
DEBU[0000] Testing port 22623 on protocol tcp
DEBU[0000] Testing port 67 on protocol udp
DEBU[0000] Testing port 80 on protocol tcp
DEBU[0000] Testing port 546 on protocol udp
DEBU[0000] Testing port 8080 on protocol tcp
DEBU[0000] Testing port 9000 on protocol tcp
DEBU[0000] Testing port 53 on protocol udp
DEBU[0000] Testing port 53 on protocol tcp
INFO[0000] Preflight checks for Ports                    Port Issues=0
INFO[0000] Running firewall checks
INFO[0001] Preflight checks for Firewall                 Firewall Issues=0
INFO[0001] Preflight Summary                             FWRules=0 PortCheck=0 SystemdCheck=0
INFO[0001] No preflight errors found
INFO[0001] Starting Containers
======================
DEBU[0001] Subset: dns:quay.io/helpernode/dns:latest
INFO[0001] Starting: dns
INFO[0001] Validationg configuration in helpernode.yaml
INFO[0001] Starting helpernode-dns

---------------------------

[root@ib-ocp4helpernodev2ipi ~]# podman ps -a
CONTAINER ID  IMAGE                           COMMAND     CREATED         STATUS             PORTS       NAMES
f4b476b84f61  quay.io/helpernode/http:latest              52 seconds ago  Up 53 seconds ago              helpernode-http

---------------------------
[root@ib-ocp4helpernodev2ipi ~]# podman version
Version:      3.4.1-dev
API Version:  3.4.1-dev
Go Version:   go1.16.7
Built:        Tue Oct 19 12:11:42 2021
OS/Arch:      linux/amd64

----
[root@ib-ocp4helpernodev2ipi ~]# cat /etc/*elease
CentOS Stream release 8
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
CentOS Stream release 8
CentOS Stream release 8
[root@ib-ocp4helpernodev2ip
------------------------------

[root@ib-ocp4helpernodev2ipi ~]# rpm -qa|grep -i fire
firewalld-0.9.3-5.el8.noarch

-------------------------------
[root@ib-ocp4helpernodev2ipi ~]# cat .helper.yaml
arch: x86_64
bootstrap:
  ipaddr: 10.30.1.39
  name: bootstrap
disabledservices:
- dhcp
- pxe
- loadbalancer
dns:
  clusterid: svc
  domain: ocp4ipiv.local
  forwarder1: 8.8.8.8
  forwarder2: 8.8.4.4
helper:
  ipaddr: 10.30.1.40
  name: ib-ocp4helpernodev2ipi
  networkifacename: ens192
ipiip:
  api: 10.30.1.48
  apps: 10.30.1.49
masters:
- ipaddr: 10.30.1.41
  name: master01
- ipaddr: 10.30.1.42
  name: master02
- ipaddr: 10.30.1.43
  name: master03
services:
  dns: true
  http: true
version: v2
workers:
- ipaddr: 10.30.1.44
  name: worker01
- ipaddr: 10.30.1.45
  name: worker02
- ipaddr: 10.30.1.46
  name: infra01
- ipaddr: 10.30.1.47
  name: infra02

-----------------

**Comment by christianh814** [comment]
Helpernodev2 is being sunsetted and that codebase is being used to build something new. For the time being, helpernodev2 should still work if you have the binary.

Taking a quick look, it seems that you're using `domain: ocp4ipiv.local` and I'm not 100% sure that's valid for BIND.
