### ISSUE TITLE
Need `\`  with new lines for the virt-install command

### ISSUE THREAD

**Issue by nishipy** [redhat-cop/ocp4-helpernode#267]
In the following step, we need `\` with new lines for the virt-install command.
https://github.com/redhat-cop/ocp4-helpernode/blob/main/docs/quickstart-ppc64le.md#create-a-centos-78-vm

**Comment by christianh814** [comment]
Thanks! I see the PR. I'll do some testing

**Comment by christianh814** [comment]
Closed by #268
