### ISSUE TITLE
ansible-playbook failure: Could not find the requested service helper-tftp: host

### ISSUE THREAD

**Issue by steve-delillo** [redhat-cop/ocp4-helpernode#269]
Hello. There must have been a change to the playbook, recently, because I have ran this playbook multiple times without seeing the following error. Can anyone tell me why we get the following error on a newly created RHEL8.3 server? Also, I cloned the repository, today, Jan 31.  I had ran the same playbook with the exact same vars.yaml file that I used a few weeks ago (except I added ipi: false) and did not hit this failure. Usually, the playbook creates and tries to start the helper-tftp service, but no longer. This is for a bare-metal install.

<img width="1341" alt="image" src="https://user-images.githubusercontent.com/84864338/151868488-a1a37b44-953a-49a4-8591-95531603cf6d.png">

~# systemctl status helper-tftp.service
Unit helper-tftp.service could not be found.

Here, we can see that the playbook did not put either of the tftp start scripts where they should be:
~# ls /usr/local/bin/start-tftp.sh
ls: cannot access '/usr/local/bin/start-tftp.sh': No such file or directory

~# ls /etc/systemd/system/helper-tftp.service
ls: cannot access '/etc/systemd/system/helper-tftp.service': No such file or directory

ftp service did start, though:
~# systemctl status tftp.service 
● tftp.service - Tftp Server
   Loaded: loaded (/usr/lib/systemd/system/tftp.service; indirect; vendor preset: disabled)
   Active: active (running) since Mon 2022-01-31 15:49:27 EST; 29s ago
     Docs: man:in.tftpd
 Main PID: 69220 (in.tftpd)
    Tasks: 1 (limit: 3295900)
   Memory: 248.0K
   CGroup: /system.slice/tftp.service
           └─69220 /usr/sbin/in.tftpd -s /var/lib/tftpboot

~# cat vars.yaml
---
disk: sda
helper:
  name: "helper"
  ipaddr: "192.100.229.190"
  networkifacename: "ens2f1"
dns:
  domain: "ocpexample.com"
  clusterid: "mycluster"
  forwarder1: "9.11.227.2"
  forwarder2: "9.0.128.5"
dhcp:
  router: "192.100.229.1"
  bcast: "192.100.229.255"
  netmask: "255.255.255.0"
  poolstart: "192.100.229.191"
  poolend: "192.100.229.195"
  ipid: "192.100.229.0"
  netmaskid: "255.255.255.0"
bootstrap:
  name: "bootstrap"
  ipaddr: "192.100.229.191"
  macaddr: "b8:ce:f6:78:2d:6f"
masters:
  - name: "master0"
    ipaddr: "192.100.229.192"
    macaddr: "b8:ce:f6:78:2d:97"
  - name: "master1"
    ipaddr: "192.100.229.193"
    macaddr: "b8:ce:f6:78:2d:8f"
  - name: "master2"
    ipaddr: "192.100.229.194"
    macaddr: "b8:ce:f6:78:25:b7"
pxe:
  generate_default: true
uefi: true
ipi: false
install_filetranspiler: false
ocp_bios: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.9/4.9.0/rhcos-4.9.0-x86_64-live-rootfs.x86_64.img"
ocp_initramfs: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.9/4.9.0/rhcos-4.9.0-x86_64-live-initramfs.x86_64.img"
ocp_install_kernel: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.9/4.9.0/rhcos-4.9.0-x86_64-live-kernel-x86_64"
ocp_client: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.9.0/openshift-client-linux-4.9.0.tar.gz"
ocp_installer: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.9.0/openshift-install-linux-4.9.0.tar.gz"
helm_source: "https://get.helm.sh/helm-v3.7.2-linux-amd64.tar.gz"

**Comment by christianh814** [comment]
Are you still having this issue?

This was actually a workaround for a bug in RHEL 7 ...so I'm not even sure this is needed anymore. I'll do some testing on my end.

In the meantime, does this happen all the time?

**Comment by steve-delillo** [comment]
Hi Christian.  I somehow got around it.  Tried a few things, but I think that this is what fixed it.

In the ocp4-helpernode/vars/main.yml, I changed both of these to false.  When I first hit the issue, I only had ipi as false.  This is a baremetal install, but the "baremetal" value may mean something else.
ipi: false
baremetal: false

**Comment by christianh814** [comment]
Ah it looks like it does need to be set on both. Wonder if it should be an `or`

https://github.com/redhat-cop/ocp4-helpernode/blob/main/tasks/main.yml#L226

Not 100% sure because I don't remember why `baremetal` is even needed if the original purpose of this playbook was specifically for Baremetal.

Glad you got it working!

**Comment by christianh814** [comment]
Closing this issue as this was fixed in #264 should merge into `main` soon.
