### ISSUE TITLE
Ansible Version Check

### ISSUE THREAD

**Issue by christianh814** [redhat-cop/ocp4-helpernode#272]
Based on issue #271 

In short, we need ansible to check itself to make sure it's running the right version. This should be under `pre_task` https://github.com/redhat-cop/ocp4-helpernode/blob/main/tasks/main.yml#L13

**Comment by RishiKumarRay** [comment]
@christianh814 Hi, i have added a taks using this command in pre task 
- name: Print ansible version
    debug:
        msg: "Ansible version is  {{ ansible_version.full }}"
and this prints the version like this
![Screenshot from 2022-02-10 09-35-48](https://user-images.githubusercontent.com/87641376/153335231-b87feb40-8742-4392-ac42-3013636fc277.png)

can i raise a PR if you verify this ?

**Comment by christianh814** [comment]
The playbook should fail if the Ansible version is less than 2.9

**Comment by RishiKumarRay** [comment]
@christianh814 i think that in that case assertion would be best see 
- name: Verify Ansible version.
    assert:
      that: "ansible_version.full is version_compare('2.9', '>=')"
      msg: >
          "You must update Ansible to at least 2.9"

**Comment by RishiKumarRay** [comment]
@christianh814 i have tested this the assetions is passing since i have 2.11 installed so shall i raise a PR ?

**Comment by christianh814** [comment]
Yup, go ahead and submit a PR against the `devel` branch

**Comment by RishiKumarRay** [comment]
@christianh814 thank you , please review
