### ISSUE TITLE
quickstart snipped for modifying registry with storageclass

### ISSUE THREAD

**Issue by therevoman** [redhat-cop/ocp4-helpernode#40]
Add a comment to the quickstart indicating that on platforms with an existing StorageClass the following patch command will modify the registry config to request a claim.

`oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"storage":{"pvc":{"claim":""}}}}'`

**Comment by rohank2502** [comment]
Will like to contribute to your mentorship. Please guide me.
